name: Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Node.js
    - name: Set up Node.js for backend
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    # Install dependencies and build the backend
    - name: Install dependencies and build backend
      run: |
        cd backend
        npm install
        npm run build

    # Set up Node.js for frontend
    - name: Set up Node.js for frontend
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    # Install dependencies and build the frontend
    - name: Install dependencies and build frontend
      run: |
        cd frontend
        npm install
        npm run build

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push backend Docker image
    - name: Build and push backend Docker image
      run: |
        cd backend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/node-backend:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/node-backend:latest

    # Build and push frontend Docker image
    - name: Build and push frontend Docker image
      run: |
        cd frontend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/vue-frontend:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/vue-frontend:latest
